/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import * as fs from 'fs';
import * as path from 'path';
import { config } from 'dotenv';
import * as readline from 'readline';

config();

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(query, resolve);
  });
}

async function configureEnvironment() {
  console.log('🔧 Dispute Resolution Module - Environment Configuration\n');

  const envPath = path.join(process.cwd(), '.env');
  let envContent = '';

  // Read existing .env file if it exists
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf-8');
  }

  const configs: Record<string, string> = {};

  // File Upload Configuration
  console.log('📁 File Upload Configuration:');
  const useS3 = await question('Use S3 for file uploads? (y/n, default: n): ');
  configs.USE_S3_UPLOAD = useS3.toLowerCase() === 'y' ? 'true' : 'false';

  if (configs.USE_S3_UPLOAD === 'true') {
    configs.S3_BUCKET = await question('S3 Bucket Name: ');
    configs.S3_REGION = await question('S3 Region (default: us-east-1): ') || 'us-east-1';
    configs.AWS_ACCESS_KEY_ID = await question('AWS Access Key ID: ');
    configs.AWS_SECRET_ACCESS_KEY = await question('AWS Secret Access Key: ');
  } else {
    configs.UPLOAD_DIR = await question('Upload Directory (default: ./uploads): ') || './uploads';
    configs.UPLOAD_BASE_URL = await question('Upload Base URL (default: http://localhost:4000/uploads): ') || 'http://localhost:4000/uploads';
  }

  console.log('\n📧 Email Notification Configuration:');
  const configureEmail = await question('Configure email notifications? (y/n, default: n): ');
  if (configureEmail.toLowerCase() === 'y') {
    configs.SMTP_HOST = await question('SMTP Host (e.g., smtp.gmail.com): ');
    configs.SMTP_PORT = await question('SMTP Port (default: 587): ') || '587';
    configs.SMTP_USER = await question('SMTP Username/Email: ');
    configs.SMTP_PASS = await question('SMTP Password/App Password: ');
    configs.SMTP_FROM = await question('From Email (default: noreply@cycle.app): ') || 'noreply@cycle.app';
  }

  console.log('\n🔔 Push Notification Configuration:');
  const configurePush = await question('Configure push notifications? (y/n, default: n): ');
  if (configurePush.toLowerCase() === 'y') {
    configs.VAPID_PUBLIC_KEY = await question('VAPID Public Key: ');
    configs.VAPID_PRIVATE_KEY = await question('VAPID Private Key: ');
    configs.VAPID_SUBJECT = await question('VAPID Subject (default: mailto:admin@cycle.app): ') || 'mailto:admin@cycle.app';
  }

  console.log('\n🌐 Frontend Configuration:');
  configs.FRONTEND_URL = await question('Frontend URL (default: http://localhost:3000): ') || 'http://localhost:3000';

  // Update or append to .env file
  const lines = envContent.split('\n');
  const newLines: string[] = [];

  // Add header comment
  newLines.push('\n# Dispute Resolution Module Configuration');
  newLines.push('# Generated by configure-dispute-env.ts');

  // Update existing configs or add new ones
  const existingKeys = new Set<string>();
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      newLines.push(line);
      continue;
    }

    const [key] = trimmed.split('=');
    if (key && configs[key]) {
      newLines.push(`${key}=${configs[key]}`);
      existingKeys.add(key);
      delete configs[key];
    } else {
      newLines.push(line);
    }
  }

  // Add new configs that weren't in the file
  for (const [key, value] of Object.entries(configs)) {
    if (value) {
      newLines.push(`${key}=${value}`);
    }
  }

  // Write updated .env file
  fs.writeFileSync(envPath, newLines.join('\n'));

  console.log('\n✅ Configuration saved to .env file!');
  console.log('\n📋 Next Steps:');
  console.log('   1. Review the .env file to ensure all values are correct');
  console.log('   2. Restart the backend server for changes to take effect');
  console.log('   3. Run test scripts to verify configuration:');
  console.log('      - npm run test:dispute-uploads');
  console.log('      - npm run test:dispute-notifications');
  console.log('      - npm run check:dispute-reminders');

  rl.close();
}

configureEnvironment().catch((error) => {
  console.error('Configuration failed:', error);
  rl.close();
  process.exit(1);
});

