/* eslint-disable @typescript-eslint/no-explicit-any */
export const mockChamas: any[] = [
  {
    id: "1",
    name: "Smart Farmers Circle",
    description:
      "Agricultural cooperative supporting local farmers with micro-loans and group savings",
    icon: "🟡",
    cover_image: "",
    is_public: true,
    lending_enabled: true,
    members_count: 1800,
    contribution_amount: 1000,
    contribution_frequency: "monthly",
    roi: 12,
    default_rate: "Low",
    type: "savings",
    tags: ["lender", "public", "monthly", "high-returns", "most-active"],
    activity_score: 95,
  },
  {
    id: "2",
    name: "Tech Entrepreneurs Hub",
    description:
      "Supporting tech startups through collective investment and networking opportunities",
    icon: "💻",
    cover_image: "",
    is_public: true,
    lending_enabled: true,
    members_count: 450,
    contribution_amount: 5000,
    contribution_frequency: "monthly",
    roi: 18,
    default_rate: "Medium",
    type: "investment",
    tags: [
      "investment",
      "lender",
      "public",
      "monthly",
      "high-returns",
      "top-rated",
    ],
    activity_score: 92,
  },
  {
    id: "3",
    name: "Women Empowerment Fund",
    description:
      "Empowering women through financial independence and business development support",
    icon: "👩",
    cover_image: "",
    is_public: true,
    lending_enabled: false,
    members_count: 2200,
    contribution_amount: 2000,
    contribution_frequency: "monthly",
    roi: 10,
    default_rate: "Low",
    type: "savings",
    tags: [
      "savings-only",
      "women",
      "public",
      "monthly",
      "most-active",
      "top-rated",
    ],
    activity_score: 98,
  },
  {
    id: "4",
    name: "Youth Investment Club",
    description:
      "Young professionals building wealth together through smart investing",
    icon: "🚀",
    cover_image: "",
    type: "investment",
    tags: ["investment", "public", "weekly", "high-returns"],
    activity_score: 85,
    is_public: false,
    lending_enabled: true,
    members_count: 120,
    contribution_amount: 10000,
    contribution_frequency: "monthly",
    roi: 22,
    default_rate: "High",
  },
  {
    id: "5",
    name: "Boda Boda Sacco",
    description:
      "Motorcycle taxi operators saving for asset acquisition and emergency funds",
    icon: "🏍️",
    cover_image: "",
    is_public: true,
    lending_enabled: true,
    members_count: 3500,
    contribution_amount: 500,
    contribution_frequency: "weekly",
    roi: 8,
    default_rate: "Low",
    type: "savings",
    tags: ["lender", "public", "weekly", "most-active", "men"],
    activity_score: 88,
  },
  {
    id: "6",
    name: "Business Growth Fund",
    description:
      "SME owners pooling resources for expansion and inventory financing",
    icon: "📈",
    cover_image: "",
    is_public: false,
    lending_enabled: true,
    members_count: 85,
    contribution_amount: 15000,
    contribution_frequency: "monthly",
    roi: 25,
    default_rate: "Medium",
    type: "investment",
    tags: ["investment", "lender", "private", "monthly", "high-returns"],
    activity_score: 80,
  },
  {
    id: "7",
    name: "Teachers Welfare Group",
    description:
      "Educators building financial security through collective savings and investment",
    icon: "📚",
    cover_image: "",
    is_public: true,
    lending_enabled: false,
    members_count: 680,
    contribution_amount: 3000,
    contribution_frequency: "monthly",
    roi: 11,
    default_rate: "Low",
    type: "savings",
    tags: ["savings-only", "public", "monthly"],
    activity_score: 75,
  },
  {
    id: "8",
    name: "Mama Mboga Collective",
    description:
      "Market vendors supporting each other with daily savings and micro-credit",
    icon: "🥬",
    cover_image: "",
    is_public: true,
    lending_enabled: true,
    members_count: 1200,
    contribution_amount: 200,
    contribution_frequency: "weekly",
    roi: 9,
    default_rate: "Low",
    type: "savings",
    tags: ["lender", "women", "public", "weekly", "most-active"],
    activity_score: 90,
  },
  {
    id: "9",
    name: "Real Estate Investors",
    description:
      "Property investment group pooling capital for land and development projects",
    icon: "🏘️",
    cover_image: "",
    is_public: false,
    lending_enabled: true,
    members_count: 45,
    contribution_amount: 50000,
    contribution_frequency: "monthly",
    roi: 30,
    default_rate: "High",
    type: "investment",
    tags: [
      "investment",
      "lender",
      "private",
      "monthly",
      "high-returns",
      "top-rated",
    ],
    activity_score: 92,
  },
  {
    id: "10",
    name: "Health Workers Fund",
    description:
      "Medical professionals saving for continuing education and equipment",
    icon: "⚕️",
    cover_image: "",
    is_public: true,
    lending_enabled: false,
    members_count: 320,
    contribution_amount: 4000,
    contribution_frequency: "monthly",
    roi: 13,
    default_rate: "Low",
    type: "savings",
    tags: ["savings-only", "public", "monthly", "high-returns"],
    activity_score: 78,
  },
  {
    id: "11",
    name: "Freelancers Alliance",
    description:
      "Independent contractors building financial stability through group savings",
    icon: "💼",
    cover_image: "",
    is_public: true,
    lending_enabled: true,
    members_count: 890,
    contribution_amount: 2500,
    contribution_frequency: "monthly",
    roi: 15,
    default_rate: "Medium",
    type: "savings",
    tags: ["lender", "public", "monthly", "high-returns", "most-active"],
    activity_score: 87,
  },
  {
    id: "12",
    name: "Church Welfare Group",
    description:
      "Faith-based community supporting members with emergency funds and loans",
    icon: "⛪",
    cover_image: "",
    is_public: false,
    lending_enabled: true,
    members_count: 560,
    contribution_amount: 1500,
    contribution_frequency: "monthly",
    roi: 7,
    default_rate: "Low",
    type: "savings",
    tags: ["lender", "private", "monthly"],
    activity_score: 82,
  },
];
